# Generated by Django 4.2.30 on 2026-10-05 13:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('committee_member', 'Committee Member'), ('external_examiner', 'External Examiner'), ('admin', 'Admin')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'app_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('BACHELOR', 'Cử nhân'), ('ENGINEER', 'Kỹ sư'), ('BOTH', 'Cả Cử nhân & Kỹ sư')], default='BACHELOR', max_length=50)),
                ('current_stage', models.CharField(choices=[('PHASE_1_SETUP', 'GĐ1: Khởi tạo đợt & Thiết lập dữ liệu'), ('PHASE_2_ALLOCATING', 'GĐ2: Đang phân công GVHD'), ('PHASE_2_LOCKED', 'GĐ2: Khoa đã chốt phân công'), ('PHASE_3_TOPIC', 'GĐ3: Xây dựng & Phê duyệt đề tài'), ('PHASE_4_ELIGIBILITY', 'GĐ4: Xét điều kiện làm đồ án'), ('PHASE_5_IN_PROGRESS', 'GĐ5: Đang thực hiện đồ án'), ('PHASE_6_DEFENSE', 'GĐ6: Xét bảo vệ & Hội đồng'), ('COMPLETED', 'Hoàn tất: Đã kết thúc đợt đồ án')], default='PHASE_1_SETUP', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_allocation_published', models.BooleanField(default=False)),
                ('allocation_published_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_academicbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('VIET_ANH', 'Công nghệ thông tin Việt - Anh'), ('DAI_TRA', 'Công nghệ thông tin Đại trà'), ('KHMT', 'Khoa học máy tính'), ('KHOA_CU', 'Sinh viên Khóa cũ')], default='DAI_TRA', max_length=50)),
                ('education_program', models.CharField(choices=[('BACHELOR', 'Cử nhân'), ('ENGINEER', 'Kỹ sư')], default='BACHELOR', max_length=50)),
                ('class_group', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='app.academicbatch')),
            ],
            options={
                'db_table': 'app_courseclass',
                'ordering': ['class_code'],
            },
        ),
        migrations.CreateModel(
            name='DefenseCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_number', models.IntegerField(default=1)),
                ('council_name', models.CharField(max_length=255)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.CharField(choices=[('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều')], default='MORNING', max_length=50)),
                ('defense_room', models.CharField(blank=True, max_length=100, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_councils', to='app.academicbatch')),
            ],
            options={
                'db_table': 'app_defensecouncil',
                'ordering': ['batch', 'council_number'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_department',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GraduationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title_vi', models.CharField(max_length=500)),
                ('topic_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Đã phân GVHD'), ('OUTLINE_PENDING', 'Chờ duyệt đề cương'), ('OUTLINE_REVISION', 'Yêu cầu sửa đề cương'), ('OUTLINE_APPROVED', 'Đề cương đã duyệt'), ('IN_PROGRESS', 'Đang thực hiện đồ án'), ('DEFENSE_READY', 'Đủ điều kiện bảo vệ'), ('PASSED', 'Bảo vệ thành công - Đạt'), ('FAILED', 'Không đạt'), ('DEFERRED', 'Bảo lưu đồ án'), ('DISQUALIFIED', 'Bị loại khỏi đợt')], default='ALLOCATED', max_length=50)),
                ('topic_review_status', models.CharField(choices=[('DRAFT', 'Bản nháp (GV & SV đang xây dựng)'), ('GV_CONFIRMED', 'Giảng viên đã xác nhận'), ('APPROVED', 'Khoa đã phê duyệt đề tài'), ('REVISION_REQUIRED', 'Khoa yêu cầu chỉnh sửa lại đề tài')], default='DRAFT', max_length=50)),
                ('topic_revision_notes', models.TextField(blank=True, null=True)),
                ('outline_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('initial_eligibility', models.CharField(choices=[('PENDING', 'Chưa xét điều kiện'), ('ELIGIBLE', 'Đủ điều kiện làm đồ án'), ('INELIGIBLE', 'Không đủ điều kiện làm đồ án'), ('FORCE_APPROVED', 'Khoa đặc cách cho làm đồ án (Force Approve)'), ('DISQUALIFIED', 'Loại khỏi đợt đồ án')], default='PENDING', max_length=50)),
                ('ineligibility_reason', models.TextField(blank=True, null=True)),
                ('gpa_score', models.FloatField(blank=True, null=True)),
                ('debt_credits', models.IntegerField(default=0)),
                ('force_approved_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_defense_confirmed', models.BooleanField(default=False)),
                ('final_academic_eligibility', models.CharField(choices=[('PENDING', 'Chờ xét học vụ cuối'), ('ELIGIBLE', 'Đủ điều kiện học vụ cuối'), ('INELIGIBLE', 'Không đủ điều kiện học vụ cuối')], default='PENDING', max_length=50)),
                ('final_academic_notes', models.TextField(blank=True, null=True)),
                ('deferral_status', models.CharField(choices=[('NONE', 'Không bảo lưu'), ('REQUESTED', 'Đơn xin bảo lưu chờ duyệt'), ('APPROVED', 'Khoa đã duyệt bảo lưu'), ('REJECTED', 'Không duyệt bảo lưu (Loại khỏi đợt)')], default='NONE', max_length=50)),
                ('deferral_reason', models.TextField(blank=True, null=True)),
                ('deferral_decided_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_score', models.FloatField(blank=True, null=True)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('is_eligible_for_defense', models.BooleanField(default=False)),
                ('reviewer_score', models.FloatField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_projects', to='app.academicbatch')),
                ('council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.defensecouncil')),
                ('force_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_approved_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_graduationproject',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_projectcategories',
            },
        ),
        migrations.CreateModel(
            name='ProjectTopicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_projecttopicarea',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('education_program', models.CharField(choices=[('BACHELOR', 'Cử nhân'), ('ENGINEER', 'Kỹ sư')], default='BACHELOR', max_length=50)),
                ('academic_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.academicbatch')),
                ('course_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.courseclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_student',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(max_length=100, unique=True)),
                ('research_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_background', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('academic_title', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_rank_multiplier', models.FloatField(default=1.0)),
                ('is_external', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, related_name='supervisors', to='app.projectcategories')),
                ('department_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_supervisor',
            },
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_criteria', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_preferences', to='app.academicbatch')),
                ('preference_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nv1_students', to='app.supervisor')),
                ('preference_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nv2_students', to='app.supervisor')),
                ('preference_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nv3_students', to='app.supervisor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_record', to='app.student')),
                ('topic_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='app.projecttopicarea')),
            ],
            options={
                'db_table': 'app_studentpreference',
            },
        ),
        migrations.CreateModel(
            name='OutlineReviewGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_review_groups', to='app.academicbatch')),
                ('members', models.ManyToManyField(blank=True, related_name='outline_groups', to='app.supervisor')),
            ],
            options={
                'db_table': 'app_outlinereviewgroup',
            },
        ),
        migrations.CreateModel(
            name='OutlineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_file', models.FileField(blank=True, null=True, upload_to='outlines/')),
                ('verdict', models.CharField(choices=[('PENDING', 'Chờ xét duyệt'), ('APPROVED', 'Đạt yêu cầu'), ('REVISION_REQUIRED', 'Yêu cầu chỉnh sửa'), ('REJECTED', 'Không đạt / Hủy đề tài')], default='PENDING', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline_review', to='app.graduationproject')),
                ('review_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_outlines', to='app.outlinereviewgroup')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_outline_reviews', to='app.supervisor')),
            ],
            options={
                'db_table': 'app_outlinereview',
            },
        ),
        migrations.CreateModel(
            name='InternshipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interning', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tentative_title', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_submissions', to='app.academicbatch')),
                ('preferred_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_students', to='app.supervisor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_info', to='app.student')),
                ('topic_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='app.projecttopicarea')),
            ],
            options={
                'db_table': 'app_internshipinfo',
            },
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_graduation_projects', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_project', to='app.student'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_graduation_projects', to='app.supervisor'),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='topic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.projecttopicarea'),
        ),
        migrations.CreateModel(
            name='FinalGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_score', models.FloatField(blank=True, null=True)),
                ('reviewer_score', models.FloatField(blank=True, null=True)),
                ('council_avg_score', models.FloatField(blank=True, null=True)),
                ('final_score_10', models.FloatField(blank=True, null=True)),
                ('final_score_4', models.FloatField(blank=True, null=True)),
                ('final_letter_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_summary', to='app.graduationproject')),
            ],
            options={
                'db_table': 'app_finalgradesummary',
            },
        ),
        migrations.CreateModel(
            name='EvaluationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_supervisor', models.FloatField(default=0.4)),
                ('weight_reviewer', models.FloatField(default=0.2)),
                ('weight_council', models.FloatField(default=0.4)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_policy', to='app.academicbatch')),
            ],
            options={
                'db_table': 'app_evaluationpolicy',
            },
        ),
        migrations.CreateModel(
            name='DefenseScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=1)),
                ('slot_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='app.defensecouncil')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slot', to='app.graduationproject')),
            ],
            options={
                'db_table': 'app_defensescheduleslot',
                'ordering': ['slot_date', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHAIR', 'Chủ tịch hội đồng'), ('SECRETARY', 'Ủy viên, Thư ký'), ('MEMBER', 'Ủy viên'), ('EXTERNAL_MEMBER', 'Ủy viên ngoài trường')], default='MEMBER', max_length=50)),
                ('external_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.defensecouncil')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_memberships', to='app.supervisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_councilmember',
                'unique_together': {('council', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('evaluation_update', 'Evaluation Update'), ('document_status_change', 'Document Status Change'), ('group_status_change', 'Group Status Change'), ('supervisor_request_update', 'Supervisor Request Update'), ('admin_user_update', 'Admin User Update')], default='evaluation_update', max_length=50)),
                ('evaluation_type', models.CharField(blank=True, choices=[('scope_document', 'Scope Document'), ('srs_supervisor', 'SRS Supervisor'), ('srs_committee', 'SRS Committee Member'), ('sdd_supervisor', 'SDD Supervisor'), ('sdd_committee', 'SDD Committee Member'), ('evaluation3_supervisor', 'Evaluation 3 Supervisor'), ('evaluation3_committee', 'Evaluation 3 Committee Member'), ('evaluation4_supervisor', 'Evaluation 4 Supervisor'), ('evaluation4_committee', 'Evaluation 4 Committee Member')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('summary_content', models.TextField()),
                ('planned_tasks', models.TextField(blank=True, null=True)),
                ('git_commit_link', models.URLField(blank=True, max_length=500, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='weekly_reports/')),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('supervisor_rating', models.CharField(choices=[('PENDING', 'Chưa đánh giá'), ('GOOD', 'Tốt / Đạt tiến độ'), ('ACCEPTABLE', 'Chấp nhận được'), ('LATE', 'Chậm tiến độ'), ('UNSATISFACTORY', 'Không đạt yêu cầu')], default='PENDING', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='app.graduationproject')),
            ],
            options={
                'db_table': 'app_weeklyprogressreport',
                'unique_together': {('project', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('base_quota', models.IntegerField(default=5)),
                ('rank_multiplier', models.FloatField(default=1.0)),
                ('viet_anh_quota', models.IntegerField(default=0)),
                ('general_cntt_quota', models.IntegerField(default=0)),
                ('max_total_quota', models.IntegerField(default=0)),
                ('current_assigned', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_quotas', to='app.academicbatch')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='app.supervisor')),
            ],
            options={
                'db_table': 'app_supervisorquota',
                'unique_together': {('supervisor', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='CouncilLiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_presentation', models.FloatField(default=0.0)),
                ('score_content', models.FloatField(default=0.0)),
                ('score_qa', models.FloatField(default=0.0)),
                ('score_demo', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_scores', to='app.defensecouncil')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to='app.councilmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_scores', to='app.graduationproject')),
            ],
            options={
                'db_table': 'app_councillivescore',
                'unique_together': {('project', 'member')},
            },
        ),
    ]
